version: '3.5'

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins'
    restart: always
    ports:
      - '8090:8080'
      - '50000:50000'
    volumes:
      - $pwd/jenkins_home:/var/jenkins_home

