version: '2'
services:
  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'
  gateway-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=

  microservicio1-app:
    image: microservicio1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://microservicio1-postgresql:5432/microservicio1'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  microservicio1-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=microservicio1
      - POSTGRES_PASSWORD=

  uaa-app:
    image: uaa
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://uaa-postgresql:5432/uaa'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://uaa-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://uaa-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
  uaa-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=uaa
      - POSTGRES_PASSWORD=
  uaa-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
